name: constellation

on:
  push:
  pull_request:

jobs:

  compile:
    name: "Try to compile the project"
    runs-on: self-hosted
    env:
      CONSTELLATION_CI: 1
      JAVA_TOOL_OPTIONS: -Xmx4G -Xss8M
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile
      run: sbt "Test / compile"

  test:
    needs: [compile]
    name: "Run test configurations"
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        config: [
            "00", "01", "02", "03", "04", "05", "06", "07", "08", "09",
            "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
            "20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
            "30", "31", "32", "33", "34", "35", "36", "37", "38", "39",
            "40", "41", "42", "43", "44", "45", "46", "47", "48", "49",
            "50", "51", "52", "53", "54", "55", "56", "57", "58", "59",
            "60", "61", "62", "63", "64", "65", "66", "67", "68", "69",
            "TL00", "TL01", "TL02", "TL03", "TL04", "TL05",
            "AXI400", "AXI401", "AXI402", "AXI403"
        ]
    env:
      CONSTELLATION_CI: 1
      JAVA_TOOL_OPTIONS: -Xmx4G -Xss8M

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile
      run: sbt compile

    - name: Unit Tests
      run: sbt "testOnly constellation.NoCTest${{ matrix.config }}"
